# Generated by Django 4.0.6 on 2022-08-23 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Mails',
        ),
    ]
