# Generated by Django 4.0.6 on 2022-08-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_rename_mails_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='message',
            field=models.CharField(max_length=5000),
        ),
    ]
